### ISSUE TITLE
Allow number-reset-level to be 0

### ISSUE THREAD

**Issue by deb75** [fncokg/pandoc-tex-numbering#2]
I did set `number-reset-level` to 0 because I want to have the simplest numbering of equations : (1)  (2) .... (10) ...

This nearly does the job as I get : 
(.1)   (.2) .... (.10) ...

Is it possible to remove the dot before the equation number when no section numbering is required ?

Regards

**Comment by fncokg** [comment]
Of course, this should be seen as a bug and has been fixed in [commit ddec0ff](https://github.com/fncokg/pandoc-tex-numbering/commit/ddec0ff99ec6bd0a30c503fc51c86d4925900427)
